dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"

services: postgresql

env:
  - DJANGO=2.1.2

before_install:
  - export DJANGO_SETTINGS_MODULE=django_restaurants.settings
  - export PYTHONPATH=$HOME/builds/dawidbudzynski/restaurant_finder_python_django/backend
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE travis_db;" -U postgres

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py collectstatic
  - coverage run --source='/backend' manage.py test

after_success:
  coverage report -m