version: "3.2"
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    networks:
      - restaurant_network
    stdin_open: true
    tty: true
    command: python3 manage.py runserver 0.0.0.0:8000
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - restaurant_network
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    command: npm start
  memcached:
    image: 'bitnami/memcached:latest'
    ports:
      - '0.0.0.0:11211:11211'
    networks:
      - restaurant_network
networks:
  restaurant_network: